### ISSUE TITLE
PixelIsPoint vs. PixelIsArea

### ISSUE THREAD

**Issue by tedhabermann** [opengeospatial/geotiff#4]
This problem is described by Frank Warmerdam on the [Refining GeoTIFF](http://trac.osgeo.org/geotiff/wiki/RefiningGeoTIFF) page.

The [GeoTIFF Specification](http://www.remotesensing.org/geotiff/spec/geotiffhome.html) was somewhat vague on the implications of using and in 2.5.2.2. Some users fell into the trap of thinking that these were only a sampling technique clue and did not affect the real coordinate system. This is not the evolved industry consensus, and the specification needs to make this very clear. Some detail on this issue is captured [here](http://trac.osgeo.org/gdal/wiki/rfc33_gtiff_pixelispoint).

**Comment by rouault** [comment]
Note: I noticed there was an issue in the DGIWG profile about the georeferencing in the PixelIsArea case that @EmDevys addressed recently

**Comment by EmDevys** [comment]
Even and all
This issue is being changed in a revised 2.2 version that is about to be sent out for publication. This version should (shortly) replace version 2.1, and align DGIWG GeoTIFF with GeoTIFF practice.

Note: it should be noted that this GeoTIFF “corner convention for area pixel” is not in sync with the usual OGC convention, which is “center of pixel”. This should be clarified / made explicit when OGC is doing the revision.

Emmanuel

De : Even Rouault [mailto:notifications@github.com]
Envoyé : lundi 13 novembre 2017 18:55
À : opengeospatial/geotiff
Cc : Emmanuel Devys; Mention
Objet : Re: [opengeospatial/geotiff] PixelIsPoint vs. PixelIsArea (#4)


Note: I noticed there was an issue in the DGIWG profile about the georeferencing in the PixelIsArea case that @EmDevys<https://github.com/emdevys> addressed recently

**Comment by max-martinez** [comment]
The reference to https://github.com/opengeospatial/geotiff/issues/55 relates to the question "should the spec actually allow people to use a RasterPixelIsArea raster space if they are only specifying tie points?". When specifying merely tie points, there is no scale to be found (no PixelScale and no ModelTransformation). Thus, what exactly would be the meaning of the "area" being insisted upon in a PixelIsArea raster space?

**Comment by EmDevys** [comment]
In case of mere Tie points GeoTIFF, the PixelIsPoint Raster space seems more adequate to me, isn't it?
If there is a need of clarification, Annex B could be adjusted. If so, could you clarify and propose some contribution?

**Comment by rouault** [comment]
I don't think that PixelIsArea is less relevant in the case of tie points only. The pixels may still be considred as having an area. It is just it is not known and might be non constant if the image is not ortho-rectified. GDAL can typically handle both conventions (as it exposes all georeferencing in a PixelIsArea convention, it will add 0.5 to the I and J value of the tiepoints it reports to the user when the GeoTIFF is PixelIsPoint. Ignore this remark if it brings more confusion than clarity :-))
That said, I'm not against a recommendation to use PixelIsPoint for that case if that seems more adequate.
