### ISSUE TITLE
Missing requirement(s) for GeoKeyDirectoryTag version numbers

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geotiff#53]
We currently have those requirements
```
Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.count The GeoKeyDirectoryTag SHALL include at least 4 keys (short integers) as header information

Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.keyDirectoryVersion The first unsigned short integer in the GeoKeyDirectoryTag SHALL hold the KeyDirectoryVersion.

Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.keyRevision The second unsigned short integer in the GeoKeyDirectoryTag SHALL hold the KeyRevision.

Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.minorRevision The third unsigned short integer in the GeoKeyDirectoryTag SHALL hold the MinorRevision.

Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.minorRevisionValue The MinorRevision for this standard SHALL be 1.0.
```

To reflect the current practice (and the 1995 doc), there is missing requirements to specify that:
- KeyDirectoryVersion should be 1 (this is a requirement of http://geotiff.maptools.org/spec/geotiff2.4.html#2.4)
- KeyRevision should be 1
- MinorRevision should be 0 (the last requirement minorRevisionValue tries to express that, but in a confusing way since '1.0' is not a valid number of a unsigned short)

**Comment by EmDevys** [comment]
I would agree for GeoTIFF data fully conformant to the 1995 (existing specification).
For the revised version, MinorRevision should presumably be 1. So this KeyRevision.MinorRevision would be 1.1

**Comment by EmDevys** [comment]
Even
I would agree for GeoTIFF data fully conformant to the 1995 (existing specification).
For the revised version, MinorRevision should presumably be 1. So this KeyRevision.MinorRevision would be 1.1.

I’ve commented this issue #53 on the github. To be further discussed by the SWG.

De : Even Rouault [mailto:notifications@github.com]
Envoyé : vendredi 21 décembre 2018 15:08
À : opengeospatial/geotiff
Cc : Subscribed
Objet : [opengeospatial/geotiff] Missing requirement(s) for GeoKeyDirectoryTag version numbers (#53)


We currently have those requirements

Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.count The GeoKeyDirectoryTag SHALL include at least 4 keys (short integers) as header information



Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.keyDirectoryVersion The first unsigned short integer in the GeoKeyDirectoryTag SHALL hold the KeyDirectoryVersion.



Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.keyRevision The second unsigned short integer in the GeoKeyDirectoryTag SHALL hold the KeyRevision.



Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.minorRevision The third unsigned short integer in the GeoKeyDirectoryTag SHALL hold the MinorRevision.



Requirement | http://www.opengis.net/spec/GeoTIFF/0.0/GeoKeyDirectoryTag.minorRevisionValue The MinorRevision for this standard SHALL be 1.0.

To reflect the current practice (and the 1995 doc), there is missing requirements to specify that:

  *   KeyDirectoryVersion should be 1 (this is a requirement of http://geotiff.maptools.org/spec/geotiff2.4.html#2.4)
  *   KeyRevision should be 1
  *   MinorRevision should be 0 (the last requirement minorRevisionValue tries to express that, but in a confusing way since '1.0' is not a valid number of a unsigned short)

**Comment by cmheazel** [comment]
Proposal: We add two requirements
 1) Requirement KeyDirectoryVersionValue which would be set to 1
 2) Requirement KeyRevisionValue which would be set to 1 
Then we restrict the MinorRevisionValue requirement to 0 or 1 (0 = the 1995 version.  By allowing 0 we are indicating that previous implementations are compliant except as described in a section TBD)
Any Objection to Unanimous Consent?

**Comment by max-martinez** [comment]
No objection. But I noticed you are using wording like "Note: Original ranges were...." which you might want to change to "Note: 1.0 ranges were...."

**Comment by EmDevys** [comment]
I fully support

De : Chuck Heazel [mailto:notifications@github.com]
Envoyé : vendredi 21 décembre 2018 19:10
À : opengeospatial/geotiff
Cc : Emmanuel Devys; Comment
Objet : Re: [opengeospatial/geotiff] Missing requirement(s) for GeoKeyDirectoryTag version numbers (#53)


Proposal: We add two requirements

  1.  Requirement KeyDirectoryVersionValue which would be set to 1
  2.  Requirement KeyRevisionValue which would be set to 1
Then we restrict the MinorRevisionValue requirement to 0 or 1 (0 = the 1995 version. By allowing 0 we are indicating that previous implementations are compliant except as described in a section TBD)
Any Objection to Unanimous Consent?
