### ISSUE TITLE
Remark on standard draft Jan 16 2019: confusion about 1.0 version number

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geotiff#68]
"1. Scope""mentions "It should therefore be backward compatible with the 1.0 version, both for coordinate reference systems based on EPSG register codes, or user-defined coordinate reference systems." and "2. Conformance" mentions "This version 1.0 of the OGC® GeoTIFF standard is a formalized version of the GeoTIFF specification currently in common use. Any discrepancies between this specification and the community GeoTIFF standard identified in Chapter 3 should be brought to the attention of the OGC® for resolution."

This wil be confusing for readers without full background. In 1) (and in many/most other places of the new document), 1.0 refers to the 1995 spec. In 2) to the current OGC spec.

- Could we decide that the OGC spec is called 1.1 to align with the GeoTIFF keys ? There wouldn't be any OGC GeoTIFF 1.0 to avoid confusion with the 1995 GeoTIFF 1.0 spec
- "it should therefore be backward compatible with the 1.0 version" and "Any discrepancies between this specification and the community GeoTIFF standard identified in Chapter 3" aren't really true. There are known gaps between 1.0 and 1.1, particularly on the vertical part.

**Comment by EmDevys** [comment]
I agree that 1995 GeoTIFF 1.0 is the naming / title of legacy GeoTIFF standard.
IMHO, this OGC GeoTIFF specification should make it clear about this verison / revision as early as Introduction (which is just informative) and Scope (or in a sub-section of clause 1: This version.
Clause 2 confoamnce should only address conformance statements for this version, and address Annex A.
The sentence "Any discrepancies between this specification and the community GeoTIFF standard identified in Chapter 3 should be brought to the attention of the OGC® for resolution" has nothing to do with conformance clause, and seems to me a weird statement in a standard. This is a message that may be setn to reviweers for internal SWG review, or public RFC ... but should be suppressed.
Having said that, I agree with the proposal to name this OGC GeoTIFF version 1.1 (in order to avoid any ambiguity with 1995 GeoTIFF 1.0). In addition the major/minor revision tags are 1.1, so seems better (IMHO) to align the version numbering, unless there is any objection.

**Comment by EmDevys** [comment]
Unless any objection, I propose to delete the last paragraph of clause 2:
This version 1.0 of the OGC® GeoTIFF standard is a formalized version of the GeoTIFF specification
currently in common use. Any discrepancies between this specification and the community
GeoTIFF standard identified in Chapter 3 should be brought to the attention of the OGC® for
resolution.
(For the reasons provided above)

**Comment by cmheazel** [comment]
Concur
