### ISSUE TITLE
New Projection Methods and Projection Parameters

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#89]
Since the original GeoTIFF specification a number of GeoTIFF projection methods and parameters have been added. These should also be reviewed, and if they seem reasonable and in somewhat well understood and common use they should be captured in the specification.

**Comment by EmDevys** [comment]
This issue was issue #3. and has been closed Sept. 2019 as addressed in revision 1.1. GeoTIFF 1.1 is based on EPSG standardized projection parameters, and allows user-defined projection (and documents this in Annex B). GeoTIFF spec. is not aimed at specifying specific projection capabilities and projection
=> confirmation of the need to close this re-opened issue
