### ISSUE TITLE
Vertical Coordinate Systems

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#92]
The information on vertical coordinate systems in the GeoTIFF specification was pretty slim (see 2.5.3.4 and 6.3.4) and and it has taken a long time to establish industry practice on this topic. An effort has been made to suggest best practice at VerticalCS and after review I suggest this make it’s way into the specification in some form.

**Comment by EmDevys** [comment]
This issue was issue #7 and has led to significant improvement (this is a key added-value of GeoTIFF 1.1 vs GeoTIFF 1.0), after discussion with various members.
The resulting requirements on VerticalCS and VerticalGeoKey in 1.1 work for elevation grids, samples have been produced.
If something could be added, would probably be best practise, but IMHO the OGC GeoTIFF 1.1 is sufficient.
=> proposal to close (again) this issue, after checking with members / actors that whether there is still guidance to be provided.
