### ISSUE TITLE
Axis Order

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#94]
The GeoTIFF spec is vague on axis order issues. Some suggestions on this are made in the FAQ and some conclusion should likely be codified in the specification - hopefully not in a way that flies in the face of actual industry practice.

**Comment by EmDevys** [comment]
This issue was previously #73 on GeoTIFF 1.0 and has been addressed in OGC GeoTIFF 1.1 in:
- Requirements 10.4 and 10.5
- Note in 7.5
- guidance in B.2.3 and B.3.2.
It was closed in Sept. 2019 after discussions, because GeoTIFF 1.1 is no longer vague on this topic. If something would be missing, there should be a clear indication of what is recommended. Possibly some additional guidance.
If not, recommend to reclose this, after a call to the SWG and actors / industry in order to check that this is now sufficient.
