### ISSUE TITLE
Support for HTJ2K Support

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#97]
High Throughput JPEG 2000(HTJ2K) is a redesigned J2K format which provides much better performance than the original J2K algorithm.  A summary for this format was presented to the Defense and Intelligence DWG on March 25, 2021.  The DWG felt that a Geo-enabled form would be desirable and that we should follow the GeoTIFF model to achieve this.  The proposed approach is to:
1) separate the GeoTIFF metadata from the TIFF file.
2) generate an encoding of the GeoTIFF metadata which is compatible wit the HTJ2K format.
3) pilot one or more implementations.

**Comment by rouault** [comment]
GeoJP2 (http://fileformats.archiveteam.org/wiki/GeoJP2) is something that already exists and is applicable to the whole JPEG2000 family, being at the JP2 box level rather than at the codestream level, so either for the classic Part 1 JPEG2000 or the new Part15 HTJ2K. I don't see anything new  really needed. It should be noted that GeoJP2 is considered a bit as a deprecated approach compared to GMLJP2 (https://www.ogc.org/standards/gmljp2)

**Comment by rouault** [comment]
My recommendation: fix that issue as wontfix, or at the very least strongly coordinate with the SWG responsible for GMLJP2. There's no reason to have a different way of encoding georeferencing for regular Part-1 JPEG 2000 or for Part-15 HTJ2K. The difference between them is at the JPEG2000 codestream level, which is really an implementation detail for upper layers. GMLJP2 is capable of encoding both "known" CRS (with URN or URL), or custom ones (using GML CRS dictionaries). Using GML CRS dictionaries is probably quite complicated from an implementation point of view and has the caveat that the GML CRS encoding is based on an older version than ISO19111:2019 and is unlikely to be updated, but it exists. The GeoTIFF way to encode custom CRS has its own deficiencies (like inability to add new projection methods such as https://github.com/opengeospatial/geotiff/issues/56#issuecomment-506238420)

**Comment by EmDevys** [comment]
GeoJP2 (http://fileformats.archiveteam.org/wiki/GeoJP2) is something that already exists ... ..... It should be noted that GeoJP2 is considered a bit as a deprecated approach compared to GMLJP2 (https://www.ogc.org/standards/gmljp2)
GeoJP2 specification (a degenerate GeoTIFF file inside a uuid JPEG 2000 box) is no longer available (since Lizard Tech integration in Extensis company). It seems there is no company nor authority handling or maintaining this specification. However it is widely supported, as it seems to be realtively easy to implement (by software supporting GeoTIFF) for georeferencing imagery. Whether it is to be considered as "deprecated approach compared to GMLJP2" is to be discussed. Now that GeoTIFF is also an OGC standard, such discussion make sense in the OGC, but stakeholders having an interest in Geo JP2 exist outside the OGC.

**Comment by EmDevys** [comment]
My recommendation: fix that issue as wontfix, or at the very least strongly coordinate with the SWG responsible for GMLJP2. There's no reason to have a different way of encoding georeferencing for regular Part-1 JPEG 2000 or for Part-15 HTJ2K. The difference between them is at the JPEG2000 codestream level, which is really an implementation detail for upper layers.
------------
It seems that HTJ2K (ISO 15444-15) is compatible with JPEG 2000 (set of ISO 15444 standards), and to be considered as an extension of JPEG 2000 and its JP2 format (as well as JPX). For georeferencing HTJ2K, both the usage of GML in the asoc/XML box as specified in GMLJP2, or the usage of a degenerate GeoTIFF file inside a uuid box) appear as potential options.
I would agree that this topic (issue) should be discussed with GMLJP2.SWG in order to decide how it should be handled. Within the scope of GeoTIFF standard, it should presumably not be considered as an issue (IMHO).

**Comment by joanma747** [comment]
Funny thing could be to discuss here if the GMLJP2 strategy could (completely) replace the current approach for GeoTIFF. GeoTIFF already has a method to include a string, so it can also contain a XML fragment :-)

This idea is similar to https://github.com/opengeospatial/geotiff/issues/78

**Comment by joanma747** [comment]
There was no objection to transfer this issue to the GMLJP2 group in today telecon. It will be done in a week time if nobody objects in this group.

One of the conclusion is that there should be no reason to have a different way of encoding georeferencing for regular Part-1 JPEG 2000 or for Part-15 HTJ2K and all should use the same GMLJP2.

**Comment by joanma747** [comment]
This depends on TIFF but this beyond our capacity of control TIFF. Other formats have this capabilities and embedding in TIF could be too much. There are efforts done to support many codecs already in this direction but many libraries does not read it.
